### ISSUE TITLE
ImportError when using autouri>=0.1.3

### ISSUE THREAD

**Issue by motorny** [ENCODE-DCC/croo#24]
Dear developers team,

I am using the latest version of `croo`, and `autouri 0.1.3` was installed as a dependency.
My program fails at importing `croo` due to an import error:
```
   Traceback (most recent call last):
      File "......", line 18, in <module>
        from croo.croo import Croo
      File "....../venv/lib/python3.6/site-packages/croo/__init__.py", line 1, in <module>
        import croo.croo_args
      File "....../venv/lib/python3.6/site-packages/croo/croo_args.py", line 14, in <module>
        from autouri import logger as autouri_logger
    ImportError: cannot import name 'logger'
```
WIth `autouri == 0.1.2.1` everything works fine.

As I can see, `logger` importing was removed here
 
https://github.com/ENCODE-DCC/autouri/commit/27fdc8b49b8248be44bf8d403e55f4649b3c4049#diff-cff2da03edefd322cc30e7305960e91fL6

Best regards,
Nikita

**Comment by leepc12** [comment]
Please update your Croo.
`pip install croo --upgrade`

**Comment by motorny** [comment]
Dear @leepc12 ,

Thank you for an answer!
It worked perfectly

Best regards,
Nikita
