### ISSUE TITLE
Link/copy stdout and stderr files?

### ISSUE THREAD

**Issue by davetang** [ENCODE-DCC/croo#35]
Hi there,

thank you so much for `croo`; it does exactly what I need. I was just wondering if there is a way to refer to the `stdout` and `stderr` files generated by Cromwell in the output JSON file, so that they can be copied/linked to the output directory?

Cheers,
Dave

**Comment by leepc12** [comment]
No, `croo` does not keep the original directory structure including stdout/stderr files in it.
You need to manually parse `metadata_json["calls"]` object. Each call object has `stdout` and `stderr`.
Or use `gsutil ls` or `find -name stdout`.

**Comment by davetang** [comment]
OK, I'll write a separate script to parse the metadata file. Thanks!
