### ISSUE TITLE
Docs up to date?

### ISSUE THREAD

**Issue by guma44** [ENCODE-DCC/croo#7]
Thanks for nice package! Is this doc statement still true?

>WARNING: Unfortunately, for an output variable [OUT_VAR_NAME_IN_TASK] in a task Croo does not currently support Array[File] type. It only supports File type. task t1 { command { ... } output { Array[File] out_list # NOT SUPPORTED File out # SUPPORTED } }

Rafal

**Comment by leepc12** [comment]
Sorry, I will remove it from the doc. `Array[File]` is supported.
